var data = [
['AUDI AG', 'Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH', 1],
['Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH', 'AUDI AG', 1],
['Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH', 'Procar Automobile Verwaltungsgesellschaft mbH', 3],
['Procar Automobile Verwaltungsgesellschaft mbH', 'Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH', 3],
['Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH', 'Procar Automobile GmbH', 3],
['Procar Automobile GmbH', 'Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH', 3],
['AUDI AG', 'ADAC Beteiligungs- und Wirtschaftsdienst GmbH', 1],
['ADAC Beteiligungs- und Wirtschaftsdienst GmbH', 'AUDI AG', 1],
['ADAC Beteiligungs- und Wirtschaftsdienst GmbH', 'ADAC Finanzdienste GmbH', 2],
['ADAC Finanzdienste GmbH', 'ADAC Beteiligungs- und Wirtschaftsdienst GmbH', 2],
['ADAC Beteiligungs- und Wirtschaftsdienst GmbH', 'ADAC Stiftung Gelber Engel gGmbH', 4],
['ADAC Stiftung Gelber Engel gGmbH', 'ADAC Beteiligungs- und Wirtschaftsdienst GmbH', 4],
['ADAC Beteiligungs- und Wirtschaftsdienst GmbH', 'AD Clubreisen GmbH', 2],
['AD Clubreisen GmbH', 'ADAC Beteiligungs- und Wirtschaftsdienst GmbH', 2],
['ADAC Beteiligungs- und Wirtschaftsdienst GmbH', 'ADAC Touring GmbH', 2],
['ADAC Touring GmbH', 'ADAC Beteiligungs- und Wirtschaftsdienst GmbH', 2],
['AUDI AG', 'Dr. Ing. h.c. F. Porsche AG', 2],
['Dr. Ing. h.c. F. Porsche AG', 'AUDI AG', 2],
['Dr. Ing. h.c. F. Porsche AG', 'Porsche Holding Stuttgart GmbH', 14],
['Porsche Holding Stuttgart GmbH', 'Dr. Ing. h.c. F. Porsche AG', 14],
['Dr. Ing. h.c. F. Porsche AG', 'Porsche Siebte Vermögensverwaltung GmbH', 3],
['Porsche Siebte Vermögensverwaltung GmbH', 'Dr. Ing. h.c. F. Porsche AG', 3],
['Dr. Ing. h.c. F. Porsche AG', 'Porsche Erste Vermögensverwaltung GmbH', 5],
['Porsche Erste Vermögensverwaltung GmbH', 'Dr. Ing. h.c. F. Porsche AG', 5],
['Dr. Ing. h.c. F. Porsche AG', 'Porsche Vierte Vermögensverwaltung GmbH', 5],
['Porsche Vierte Vermögensverwaltung GmbH', 'Dr. Ing. h.c. F. Porsche AG', 5],
['Dr. Ing. h.c. F. Porsche AG', 'Porsche Deutschland GmbH', 2],
['Porsche Deutschland GmbH', 'Dr. Ing. h.c. F. Porsche AG', 2],
['Dr. Ing. h.c. F. Porsche AG', 'Porsche Automobil Holding SE', 10],
['Porsche Automobil Holding SE', 'Dr. Ing. h.c. F. Porsche AG', 10],
['Dr. Ing. h.c. F. Porsche AG', 'Porsche Niederlassung Leipzig GmbH', 3],
['Porsche Niederlassung Leipzig GmbH', 'Dr. Ing. h.c. F. Porsche AG', 3],
['Dr. Ing. h.c. F. Porsche AG', 'Porsche Beteiligung GmbH', 2],
['Porsche Beteiligung GmbH', 'Dr. Ing. h.c. F. Porsche AG', 2],
['Dr. Ing. h.c. F. Porsche AG', 'Porsche Nordamerika Holding GmbH', 3],
['Porsche Nordamerika Holding GmbH', 'Dr. Ing. h.c. F. Porsche AG', 3],
['Dr. Ing. h.c. F. Porsche AG', 'VOLKSWAGEN AG', 7],
['VOLKSWAGEN AG', 'Dr. Ing. h.c. F. Porsche AG', 7],
['AUDI AG', 'Constellium Deutschland GmbH', 1],
['Constellium Deutschland GmbH', 'AUDI AG', 1],
['Constellium Deutschland GmbH', 'Constellium Singen GmbH', 15],
['Constellium Singen GmbH', 'Constellium Deutschland GmbH', 15],
['Constellium Deutschland GmbH', 'Constellium Germany Verwaltungs GmbH', 9],
['Constellium Germany Verwaltungs GmbH', 'Constellium Deutschland GmbH', 9],
['AUDI AG', 'Constellium Singen GmbH', 1],
['Constellium Singen GmbH', 'AUDI AG', 1],
['Constellium Singen GmbH', 'Constellium Deutschland GmbH', 15],
['Constellium Deutschland GmbH', 'Constellium Singen GmbH', 15],
['Constellium Singen GmbH', 'Constellium Extrusions Burg GmbH', 2],
['Constellium Extrusions Burg GmbH', 'Constellium Singen GmbH', 2],
['Constellium Singen GmbH', '3A Composites GmbH', 3],
['3A Composites GmbH', 'Constellium Singen GmbH', 3],
['Constellium Singen GmbH', 'Constellium Extrusions Deutschland GmbH', 2],
['Constellium Extrusions Deutschland GmbH', 'Constellium Singen GmbH', 2],
['Constellium Singen GmbH', 'Constellium Extrusions Landau GmbH', 2],
['Constellium Extrusions Landau GmbH', 'Constellium Singen GmbH', 2],
['Constellium Singen GmbH', 'Constellium Germany Verwaltungs GmbH', 9],
['Constellium Germany Verwaltungs GmbH', 'Constellium Singen GmbH', 9],
['AUDI AG', 'Porsche Engineering Services GmbH', 1],
['Porsche Engineering Services GmbH', 'AUDI AG', 1],
['Porsche Engineering Services GmbH', 'Porsche Engineering Group GmbH', 4],
['Porsche Engineering Group GmbH', 'Porsche Engineering Services GmbH', 4],
['AUDI AG', 'MAN Truck & Bus AG', 2],
['MAN Truck & Bus AG', 'AUDI AG', 2],
['MAN Truck & Bus AG', 'NEOPLAN Bus GmbH', 3],
['NEOPLAN Bus GmbH', 'MAN Truck & Bus AG', 3],
['MAN Truck & Bus AG', 'MAN Finance International GmbH', 6],
['MAN Finance International GmbH', 'MAN Truck & Bus AG', 6],
['MAN Truck & Bus AG', 'MAN Diesel & Turbo SE', 16],
['MAN Diesel & Turbo SE', 'MAN Truck & Bus AG', 16],
['MAN Truck & Bus AG', 'MAN Versicherungsvermittlung GmbH', 3],
['MAN Versicherungsvermittlung GmbH', 'MAN Truck & Bus AG', 3],
['MAN Truck & Bus AG', 'MAN HR Services GmbH', 7],
['MAN HR Services GmbH', 'MAN Truck & Bus AG', 7],
['MAN Truck & Bus AG', 'MAN Service und Support GmbH', 6],
['MAN Service und Support GmbH', 'MAN Truck & Bus AG', 6],
['MAN Truck & Bus AG', 'MAN SE', 25],
['MAN SE', 'MAN Truck & Bus AG', 25],
['MAN Truck & Bus AG', 'MAN IT Services GmbH', 10],
['MAN IT Services GmbH', 'MAN Truck & Bus AG', 10],
['MAN Truck & Bus AG', 'KPMG AG Wirtschaftsprüfungsgesellschaft', 2],
['KPMG AG Wirtschaftsprüfungsgesellschaft', 'MAN Truck & Bus AG', 2],
['MAN Truck & Bus AG', 'Renk AG', 6],
['Renk AG', 'MAN Truck & Bus AG', 6],
['MAN Truck & Bus AG', 'MAN Financial Services GmbH', 4],
['MAN Financial Services GmbH', 'MAN Truck & Bus AG', 4],
['MAN Truck & Bus AG', 'MAN-Unterstützungskasse GmbH', 3],
['MAN-Unterstützungskasse GmbH', 'MAN Truck & Bus AG', 3],
['MAN Truck & Bus AG', 'Rheinmetall MAN Military Vehicles GmbH', 3],
['Rheinmetall MAN Military Vehicles GmbH', 'MAN Truck & Bus AG', 3],
['MAN Truck & Bus AG', 'MAN Truck & Bus Deutschland GmbH', 22],
['MAN Truck & Bus Deutschland GmbH', 'MAN Truck & Bus AG', 22],
['MAN Truck & Bus AG', 'MAN Verwaltungs-Gesellschaft mbH', 2],
['MAN Verwaltungs-Gesellschaft mbH', 'MAN Truck & Bus AG', 2],
['MAN Truck & Bus AG', 'MAN Grundstücksgesellschaft mbH', 3],
['MAN Grundstücksgesellschaft mbH', 'MAN Truck & Bus AG', 3],
['MAN Truck & Bus AG', 'MAN GHH Immobilien GmbH', 2],
['MAN GHH Immobilien GmbH', 'MAN Truck & Bus AG', 2],
['AUDI AG', 'Bugatti Engineering GmbH', 1],
['Bugatti Engineering GmbH', 'AUDI AG', 1],
['Bugatti Engineering GmbH', 'VOLKSWAGEN AG', 2],
['VOLKSWAGEN AG', 'Bugatti Engineering GmbH', 2],
['AUDI AG', 'Krauss-Maffei China GmbH', 1],
['Krauss-Maffei China GmbH', 'AUDI AG', 1],
['Krauss-Maffei China GmbH', 'KraussMaffei Berstorff GmbH', 5],
['KraussMaffei Berstorff GmbH', 'Krauss-Maffei China GmbH', 5],
['Krauss-Maffei China GmbH', 'KraussMaffei Technologies GmbH', 3],
['KraussMaffei Technologies GmbH', 'Krauss-Maffei China GmbH', 3],
['Krauss-Maffei China GmbH', 'KraussMaffei Automation GmbH', 2],
['KraussMaffei Automation GmbH', 'Krauss-Maffei China GmbH', 2],
['Krauss-Maffei China GmbH', 'KraussMaffei Group GmbH', 2],
['KraussMaffei Group GmbH', 'Krauss-Maffei China GmbH', 2],
['AUDI AG', 'MAN SE', 2],
['MAN SE', 'AUDI AG', 2],
['MAN SE', 'MAN IT Services GmbH', 10],
['MAN IT Services GmbH', 'MAN SE', 10],
['MAN SE', 'MAN Finance International GmbH', 8],
['MAN Finance International GmbH', 'MAN SE', 8],
['MAN SE', 'MAN Financial Services GmbH', 7],
['MAN Financial Services GmbH', 'MAN SE', 7],
['MAN SE', 'MAN Diesel & Turbo SE', 12],
['MAN Diesel & Turbo SE', 'MAN SE', 12],
['MAN SE', 'MAN Truck & Bus AG', 25],
['MAN Truck & Bus AG', 'MAN SE', 25],
['MAN SE', 'Renk AG', 4],
['Renk AG', 'MAN SE', 4],
['MAN SE', 'Webasto Thermo & Co.mfort SE', 2],
['Webasto Thermo & Co.mfort SE', 'MAN SE', 2],
['MAN SE', 'Webasto Roof & Co.mponents SE', 2],
['Webasto Roof & Co.mponents SE', 'MAN SE', 2],
['MAN SE', 'MAN Erste Beteiligungs GmbH', 5],
['MAN Erste Beteiligungs GmbH', 'MAN SE', 5],
['MAN SE', 'MAN-Unterstützungskasse GmbH', 7],
['MAN-Unterstützungskasse GmbH', 'MAN SE', 7],
['MAN SE', 'Verwaltungsgesellschaft Wasseralfingen mbH', 3],
['Verwaltungsgesellschaft Wasseralfingen mbH', 'MAN SE', 3],
['MAN SE', 'MAN Truck & Bus Deutschland GmbH', 3],
['MAN Truck & Bus Deutschland GmbH', 'MAN SE', 3],
['MAN SE', 'MAN Grundstücksgesellschaft mbH', 7],
['MAN Grundstücksgesellschaft mbH', 'MAN SE', 7],
['MAN SE', 'MAN Versicherungsvermittlung GmbH', 9],
['MAN Versicherungsvermittlung GmbH', 'MAN SE', 9],
['MAN SE', 'MAN HR Services GmbH', 10],
['MAN HR Services GmbH', 'MAN SE', 10],
['MAN SE', 'MAN GHH Immobilien GmbH', 2],
['MAN GHH Immobilien GmbH', 'MAN SE', 2],
['AUDI AG', 'Audi Vertriebsbetreuungsgesellschaft mbH', 5],
['Audi Vertriebsbetreuungsgesellschaft mbH', 'AUDI AG', 5],
['AUDI AG', 'Audi Akademie GmbH', 1],
['Audi Akademie GmbH', 'AUDI AG', 1],
['AUDI AG', 'Pierburg GmbH', 1],
['Pierburg GmbH', 'AUDI AG', 1],
['Pierburg GmbH', 'MS Motorservice International GmbH', 2],
['MS Motorservice International GmbH', 'Pierburg GmbH', 2],
['Pierburg GmbH', 'KSPG AG', 2],
['KSPG AG', 'Pierburg GmbH', 2],
['Pierburg GmbH', 'Werkzeugbau Walldürn GmbH', 2],
['Werkzeugbau Walldürn GmbH', 'Pierburg GmbH', 2],
['Pierburg GmbH', 'Pierburg Pump Technology GmbH', 14],
['Pierburg Pump Technology GmbH', 'Pierburg GmbH', 14],
['Pierburg GmbH', 'Kolbenschmidt Pierburg Innovations GmbH', 2],
['Kolbenschmidt Pierburg Innovations GmbH', 'Pierburg GmbH', 2],
['AUDI AG', 'Audi Business Innovation GmbH', 1],
['Audi Business Innovation GmbH', 'AUDI AG', 1],
['AUDI AG', 'Truck & Bus GmbH', 1],
['Truck & Bus GmbH', 'AUDI AG', 1],
['Truck & Bus GmbH', 'Porsche Siebte Vermögensverwaltung GmbH', 3],
['Porsche Siebte Vermögensverwaltung GmbH', 'Truck & Bus GmbH', 3],
['Truck & Bus GmbH', 'Porsche Erste Vermögensverwaltung GmbH', 3],
['Porsche Erste Vermögensverwaltung GmbH', 'Truck & Bus GmbH', 3],
['Truck & Bus GmbH', 'VOLKSWAGEN AG', 6],
['VOLKSWAGEN AG', 'Truck & Bus GmbH', 6],
['Truck & Bus GmbH', 'Porsche Automobil Holding SE', 2],
['Porsche Automobil Holding SE', 'Truck & Bus GmbH', 2],
['AUDI AG', 'KraussMaffei Berstorff GmbH', 1],
['KraussMaffei Berstorff GmbH', 'AUDI AG', 1],
['KraussMaffei Berstorff GmbH', 'KraussMaffei Technologies GmbH', 8],
['KraussMaffei Technologies GmbH', 'KraussMaffei Berstorff GmbH', 8],
['KraussMaffei Berstorff GmbH', 'KraussMaffei Group GmbH', 2],
['KraussMaffei Group GmbH', 'KraussMaffei Berstorff GmbH', 2],
['KraussMaffei Berstorff GmbH', 'Krauss-Maffei China GmbH', 5],
['Krauss-Maffei China GmbH', 'KraussMaffei Berstorff GmbH', 5],
['AUDI AG', 'Bayerische Motoren Werke AG', 1],
['Bayerische Motoren Werke AG', 'AUDI AG', 1],
['Bayerische Motoren Werke AG', 'BMW Vermögensverwaltungs GmbH', 2],
['BMW Vermögensverwaltungs GmbH', 'Bayerische Motoren Werke AG', 2],
['Bayerische Motoren Werke AG', 'BMW Bank GmbH', 2],
['BMW Bank GmbH', 'Bayerische Motoren Werke AG', 2],
['Bayerische Motoren Werke AG', 'BMW Hams Hall Motoren GmbH', 3],
['BMW Hams Hall Motoren GmbH', 'Bayerische Motoren Werke AG', 3],
['Bayerische Motoren Werke AG', 'BMW Vertriebszentren Verwaltungs GmbH', 2],
['BMW Vertriebszentren Verwaltungs GmbH', 'Bayerische Motoren Werke AG', 2],
['Bayerische Motoren Werke AG', 'BMW INTEC Beteiligungs GmbH', 5],
['BMW INTEC Beteiligungs GmbH', 'Bayerische Motoren Werke AG', 5],
['Bayerische Motoren Werke AG', 'BMW M GmbH Gesellschaft für individuelle Automobile', 3],
['BMW M GmbH Gesellschaft für individuelle Automobile', 'Bayerische Motoren Werke AG', 3],
['Bayerische Motoren Werke AG', 'BMW Anlagen Verwaltungs GmbH', 2],
['BMW Anlagen Verwaltungs GmbH', 'Bayerische Motoren Werke AG', 2],
['AUDI AG', 'JP Morgen UG (haftungsbeschränkt)', 1],
['JP Morgen UG (haftungsbeschränkt)', 'AUDI AG', 1],
['AUDI AG', 'LBC Premium Marketing GmbH', 1],
['LBC Premium Marketing GmbH', 'AUDI AG', 1],
['AUDI AG', 'Procar Automobile Verwaltungsgesellschaft mbH', 1],
['Procar Automobile Verwaltungsgesellschaft mbH', 'AUDI AG', 1],
['Procar Automobile Verwaltungsgesellschaft mbH', 'Procar Automobile GmbH', 7],
['Procar Automobile GmbH', 'Procar Automobile Verwaltungsgesellschaft mbH', 7],
['Procar Automobile Verwaltungsgesellschaft mbH', 'Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH', 3],
['Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH', 'Procar Automobile Verwaltungsgesellschaft mbH', 3],
['AUDI AG', 'Procar Automobile GmbH', 1],
['Procar Automobile GmbH', 'AUDI AG', 1],
['Procar Automobile GmbH', 'Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH', 3],
['Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH', 'Procar Automobile GmbH', 3],
['Procar Automobile GmbH', 'Procar Automobile Verwaltungsgesellschaft mbH', 7],
['Procar Automobile Verwaltungsgesellschaft mbH', 'Procar Automobile GmbH', 7],
['AUDI AG', 'Autovision GmbH', 1],
['Autovision GmbH', 'AUDI AG', 1],
['Autovision GmbH', 'VOLKSWAGEN AG', 2],
['VOLKSWAGEN AG', 'Autovision GmbH', 2],
['Autovision GmbH', 'Volkswagen Sachsen GmbH', 2],
['Volkswagen Sachsen GmbH', 'Autovision GmbH', 2],
['Autovision GmbH', 'Wolfsburg AG', 2],
['Wolfsburg AG', 'Autovision GmbH', 2],
['AUDI AG', 'VOLKSWAGEN AG', 10],
['VOLKSWAGEN AG', 'AUDI AG', 10],
['VOLKSWAGEN AG', 'Autovision GmbH', 2],
['Autovision GmbH', 'VOLKSWAGEN AG', 2],
['VOLKSWAGEN AG', 'Porsche Holding Stuttgart GmbH', 2],
['Porsche Holding Stuttgart GmbH', 'VOLKSWAGEN AG', 2],
['VOLKSWAGEN AG', 'Volkswagen Bank GmbH', 4],
['Volkswagen Bank GmbH', 'VOLKSWAGEN AG', 4],
['VOLKSWAGEN AG', 'Porsche Automobil Holding SE', 4],
['Porsche Automobil Holding SE', 'VOLKSWAGEN AG', 4],
['VOLKSWAGEN AG', 'Bugatti Engineering GmbH', 2],
['Bugatti Engineering GmbH', 'VOLKSWAGEN AG', 2],
['VOLKSWAGEN AG', 'Dr. Ing. h.c. F. Porsche AG', 7],
['Dr. Ing. h.c. F. Porsche AG', 'VOLKSWAGEN AG', 7],
['VOLKSWAGEN AG', 'Truck & Bus GmbH', 6],
['Truck & Bus GmbH', 'VOLKSWAGEN AG', 6],
['VOLKSWAGEN AG', 'VOLKSWAGEN FINANCIAL SERVICES AG', 4],
['VOLKSWAGEN FINANCIAL SERVICES AG', 'VOLKSWAGEN AG', 4],
['VOLKSWAGEN AG', 'Volkswagen Vertriebsbetreuungsgesellschaft mbH', 2],
['Volkswagen Vertriebsbetreuungsgesellschaft mbH', 'VOLKSWAGEN AG', 2],
];

var colors = {
"AUDI AG": "#da4480",
"3A Composites GmbH": "#5ab449",
"AD Clubreisen GmbH": "#7f5acd",
"ADAC Beteiligungs- und Wirtschaftsdienst GmbH": "#aab740",
"ADAC Finanzdienste GmbH": "#ce58c0",
"ADAC Stiftung Gelber Engel gGmbH": "#50a26e",
"ADAC Touring GmbH": "#d1434b",
"Audi Akademie GmbH": "#45c0bc",
"Audi Business Innovation GmbH": "#ce5929",
"Audi Vertriebsbetreuungsgesellschaft mbH": "#4e7bda",
"Autovision GmbH": "#d49d3c",
"BMW Anlagen Verwaltungs GmbH": "#6660a3",
"BMW Bank GmbH": "#7b853c",
"BMW Hams Hall Motoren GmbH": "#b58dde",
"BMW INTEC Beteiligungs GmbH": "#97622e",
"BMW M GmbH Gesellschaft für individuelle Automobile": "#609dd6",
"BMW Vermögensverwaltungs GmbH": "#e29074",
"BMW Vertriebszentren Verwaltungs GmbH": "#9c4b88",
"Bayerische Motoren Werke AG": "#ab505f",
"Bugatti Engineering GmbH": "#dc85b6",
"Constellium Deutschland GmbH": "#5ab449",
"Constellium Extrusions Burg GmbH": "#7f5acd",
"Constellium Extrusions Deutschland GmbH": "#aab740",
"Constellium Extrusions Landau GmbH": "#ce58c0",
"Constellium Germany Verwaltungs GmbH": "#50a26e",
"Constellium Singen GmbH": "#d1434b",
"Dr. Ing. h.c. F. Porsche AG": "#45c0bc",
"JP Morgen UG (haftungsbeschränkt)": "#ce5929",
"KPMG AG Wirtschaftsprüfungsgesellschaft": "#4e7bda",
"KSPG AG": "#d49d3c",
"Kolbenschmidt Pierburg Innovations GmbH": "#6660a3",
"Krauss-Maffei China GmbH": "#7b853c",
"KraussMaffei Automation GmbH": "#b58dde",
"KraussMaffei Berstorff GmbH": "#97622e",
"KraussMaffei Group GmbH": "#609dd6",
"KraussMaffei Technologies GmbH": "#e29074",
"LBC Premium Marketing GmbH": "#9c4b88",
"MAN Diesel & Turbo SE": "#ab505f",
"MAN Erste Beteiligungs GmbH": "#dc85b6",
"MAN Finance International GmbH": "#5ab449",
"MAN Financial Services GmbH": "#7f5acd",
"MAN GHH Immobilien GmbH": "#aab740",
"MAN Grundstücksgesellschaft mbH": "#ce58c0",
"MAN HR Services GmbH": "#50a26e",
"MAN IT Services GmbH": "#d1434b",
"MAN SE": "#45c0bc",
"MAN Service und Support GmbH": "#ce5929",
"MAN Truck & Bus AG": "#4e7bda",
"MAN Truck & Bus Deutschland GmbH": "#d49d3c",
"MAN Versicherungsvermittlung GmbH": "#6660a3",
"MAN Verwaltungs-Gesellschaft mbH": "#7b853c",
"MAN-Unterstützungskasse GmbH": "#b58dde",
"MS Motorservice International GmbH": "#97622e",
"NEOPLAN Bus GmbH": "#609dd6",
"Pierburg GmbH": "#e29074",
"Pierburg Pump Technology GmbH": "#9c4b88",
"Porsche Automobil Holding SE": "#ab505f",
"Porsche Beteiligung GmbH": "#dc85b6",
"Porsche Deutschland GmbH": "#5ab449",
"Porsche Engineering Group GmbH": "#7f5acd",
"Porsche Engineering Services GmbH": "#aab740",
"Porsche Erste Vermögensverwaltung GmbH": "#ce58c0",
"Porsche Holding Stuttgart GmbH": "#50a26e",
"Porsche Niederlassung Leipzig GmbH": "#d1434b",
"Porsche Nordamerika Holding GmbH": "#45c0bc",
"Porsche Siebte Vermögensverwaltung GmbH": "#ce5929",
"Porsche Vierte Vermögensverwaltung GmbH": "#4e7bda",
"Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH": "#d49d3c",
"Procar Automobile GmbH": "#6660a3",
"Procar Automobile Verwaltungsgesellschaft mbH": "#7b853c",
"Renk AG": "#b58dde",
"Rheinmetall MAN Military Vehicles GmbH": "#97622e",
"Truck & Bus GmbH": "#609dd6",
"VOLKSWAGEN AG": "#e29074",
"VOLKSWAGEN FINANCIAL SERVICES AG": "#9c4b88",
"Verwaltungsgesellschaft Wasseralfingen mbH": "#ab505f",
"Volkswagen Bank GmbH": "#dc85b6",
"Volkswagen Sachsen GmbH": "#5ab449",
"Volkswagen Vertriebsbetreuungsgesellschaft mbH": "#7f5acd",
"Webasto Roof & Co.mponents SE": "#aab740",
"Webasto Thermo & Co.mfort SE": "#ce58c0",
"Werkzeugbau Walldürn GmbH": "#50a26e",
"Wolfsburg AG": "#d1434b",
};

var sortOrder = [
"AUDI AG",
"3A Composites GmbH",
"AD Clubreisen GmbH",
"ADAC Beteiligungs- und Wirtschaftsdienst GmbH",
"ADAC Finanzdienste GmbH",
"ADAC Stiftung Gelber Engel gGmbH",
"ADAC Touring GmbH",
"Audi Akademie GmbH",
"Audi Business Innovation GmbH",
"Audi Vertriebsbetreuungsgesellschaft mbH",
"Autovision GmbH",
"BMW Anlagen Verwaltungs GmbH",
"BMW Bank GmbH",
"BMW Hams Hall Motoren GmbH",
"BMW INTEC Beteiligungs GmbH",
"BMW M GmbH Gesellschaft für individuelle Automobile",
"BMW Vermögensverwaltungs GmbH",
"BMW Vertriebszentren Verwaltungs GmbH",
"Bayerische Motoren Werke AG",
"Bugatti Engineering GmbH",
"Constellium Deutschland GmbH",
"Constellium Extrusions Burg GmbH",
"Constellium Extrusions Deutschland GmbH",
"Constellium Extrusions Landau GmbH",
"Constellium Germany Verwaltungs GmbH",
"Constellium Singen GmbH",
"Dr. Ing. h.c. F. Porsche AG",
"JP Morgen UG (haftungsbeschränkt)",
"KPMG AG Wirtschaftsprüfungsgesellschaft",
"KSPG AG",
"Kolbenschmidt Pierburg Innovations GmbH",
"Krauss-Maffei China GmbH",
"KraussMaffei Automation GmbH",
"KraussMaffei Berstorff GmbH",
"KraussMaffei Group GmbH",
"KraussMaffei Technologies GmbH",
"LBC Premium Marketing GmbH",
"MAN Diesel & Turbo SE",
"MAN Erste Beteiligungs GmbH",
"MAN Finance International GmbH",
"MAN Financial Services GmbH",
"MAN GHH Immobilien GmbH",
"MAN Grundstücksgesellschaft mbH",
"MAN HR Services GmbH",
"MAN IT Services GmbH",
"MAN SE",
"MAN Service und Support GmbH",
"MAN Truck & Bus AG",
"MAN Truck & Bus Deutschland GmbH",
"MAN Versicherungsvermittlung GmbH",
"MAN Verwaltungs-Gesellschaft mbH",
"MAN-Unterstützungskasse GmbH",
"MS Motorservice International GmbH",
"NEOPLAN Bus GmbH",
"Pierburg GmbH",
"Pierburg Pump Technology GmbH",
"Porsche Automobil Holding SE",
"Porsche Beteiligung GmbH",
"Porsche Deutschland GmbH",
"Porsche Engineering Group GmbH",
"Porsche Engineering Services GmbH",
"Porsche Erste Vermögensverwaltung GmbH",
"Porsche Holding Stuttgart GmbH",
"Porsche Niederlassung Leipzig GmbH",
"Porsche Nordamerika Holding GmbH",
"Porsche Siebte Vermögensverwaltung GmbH",
"Porsche Vierte Vermögensverwaltung GmbH",
"Procar Automobile Finanz-Holding Beteiligungsgesellschaft mbH",
"Procar Automobile GmbH",
"Procar Automobile Verwaltungsgesellschaft mbH",
"Renk AG",
"Rheinmetall MAN Military Vehicles GmbH",
"Truck & Bus GmbH",
"VOLKSWAGEN AG",
"VOLKSWAGEN FINANCIAL SERVICES AG",
"Verwaltungsgesellschaft Wasseralfingen mbH",
"Volkswagen Bank GmbH",
"Volkswagen Sachsen GmbH",
"Volkswagen Vertriebsbetreuungsgesellschaft mbH",
"Webasto Roof & Co.mponents SE",
"Webasto Thermo & Co.mfort SE",
"Werkzeugbau Walldürn GmbH",
"Wolfsburg AG",
];

function sort(a,b){ return d3.ascending(sortOrder.indexOf(a),sortOrder.indexOf(b)); }

var ch = viz.ch().data(data)
      .padding(.01)
      .sort(sort)
	  .innerRadius(330)
	  .outerRadius(350)
	  .duration(1000)
	  .chordOpacity(0.3)
	  .labelPadding(.03)
      .fill(function(d){ return colors[d];});

var width=1200, height=1100;

var svg = d3.select("body").append("svg").attr("height",height).attr("width",width);

svg.append("g").attr("transform", "translate(600,550)").call(ch);

// adjust height of frame in bl.ocks.org
d3.select(self.frameElement).style("height", height+"px").style("width", width+"px");     
