var data = [
['Karosseriewerke Dresden GmbH', 'Graf Treuhand GmbH Wirtschaftsprüfungsgesellschaft Steuerberatungsgesellschaft', 1],
['Graf Treuhand GmbH Wirtschaftsprüfungsgesellschaft Steuerberatungsgesellschaft', 'Karosseriewerke Dresden GmbH', 1],
['Graf Treuhand GmbH Wirtschaftsprüfungsgesellschaft Steuerberatungsgesellschaft', 'Schneider + Partner GmbH Wirtschaftsprüfungsgesellschaft Steuerberatungsgesellschaft', 2],
['Schneider + Partner GmbH Wirtschaftsprüfungsgesellschaft Steuerberatungsgesellschaft', 'Graf Treuhand GmbH Wirtschaftsprüfungsgesellschaft Steuerberatungsgesellschaft', 2],
['Karosseriewerke Dresden GmbH', 'KWD Automobiltechnik GmbH', 2],
['KWD Automobiltechnik GmbH', 'Karosseriewerke Dresden GmbH', 2],
['KWD Automobiltechnik GmbH', 'SCHNELLTRANS GmbH', 2],
['SCHNELLTRANS GmbH', 'KWD Automobiltechnik GmbH', 2],
['KWD Automobiltechnik GmbH', 'Schnellecke Logistics Wolfsburg GmbH', 2],
['Schnellecke Logistics Wolfsburg GmbH', 'KWD Automobiltechnik GmbH', 2],
['KWD Automobiltechnik GmbH', 'Schnellecke Logistics Germany GmbH', 2],
['Schnellecke Logistics Germany GmbH', 'KWD Automobiltechnik GmbH', 2],
['KWD Automobiltechnik GmbH', 'KWD Automotive Verwaltungs GmbH', 2],
['KWD Automotive Verwaltungs GmbH', 'KWD Automobiltechnik GmbH', 2],
['KWD Automobiltechnik GmbH', 'Schnellecke Logistics Dingolfing GmbH', 2],
['Schnellecke Logistics Dingolfing GmbH', 'KWD Automobiltechnik GmbH', 2],
['Karosseriewerke Dresden GmbH', 'Schnellecke Logistics Germany GmbH', 2],
['Schnellecke Logistics Germany GmbH', 'Karosseriewerke Dresden GmbH', 2],
['Schnellecke Logistics Germany GmbH', 'KWD Automotive Verwaltungs GmbH', 2],
['KWD Automotive Verwaltungs GmbH', 'Schnellecke Logistics Germany GmbH', 2],
['Schnellecke Logistics Germany GmbH', 'Schnellecke Modul- und Lieferantenzentrum GmbH', 2],
['Schnellecke Modul- und Lieferantenzentrum GmbH', 'Schnellecke Logistics Germany GmbH', 2],
['Schnellecke Logistics Germany GmbH', 'Schnellecke Logistics Wolfsburg GmbH', 2],
['Schnellecke Logistics Wolfsburg GmbH', 'Schnellecke Logistics Germany GmbH', 2],
['Schnellecke Logistics Germany GmbH', 'KWD Automobiltechnik GmbH', 2],
['KWD Automobiltechnik GmbH', 'Schnellecke Logistics Germany GmbH', 2],
['Schnellecke Logistics Germany GmbH', 'Schnellecke Sachsen GmbH', 2],
['Schnellecke Sachsen GmbH', 'Schnellecke Logistics Germany GmbH', 2],
['Karosseriewerke Dresden GmbH', 'Schnellecke Group AG & Co. KG', 1],
['Schnellecke Group AG & Co. KG', 'Karosseriewerke Dresden GmbH', 1],
['Schnellecke Group AG & Co. KG', 'Schnellecke Logistics AG & Co. KG', 9],
['Schnellecke Logistics AG & Co. KG', 'Schnellecke Group AG & Co. KG', 9],
['Karosseriewerke Dresden GmbH', 'KWD Automotive Verwaltungs GmbH', 2],
['KWD Automotive Verwaltungs GmbH', 'Karosseriewerke Dresden GmbH', 2],
['KWD Automotive Verwaltungs GmbH', 'Schnellecke Logistics Germany GmbH', 2],
['Schnellecke Logistics Germany GmbH', 'KWD Automotive Verwaltungs GmbH', 2],
['KWD Automotive Verwaltungs GmbH', 'KWD Automobiltechnik GmbH', 2],
['KWD Automobiltechnik GmbH', 'KWD Automotive Verwaltungs GmbH', 2],
['Karosseriewerke Dresden GmbH', 'Scandlines Deutschland GmbH', 1],
['Scandlines Deutschland GmbH', 'Karosseriewerke Dresden GmbH', 1],
['Scandlines Deutschland GmbH', 'Scandlines Participation Verwaltungs GmbH', 3],
['Scandlines Participation Verwaltungs GmbH', 'Scandlines Deutschland GmbH', 3],
['Scandlines Deutschland GmbH', 'ScanRo GmbH', 3],
['ScanRo GmbH', 'Scandlines Deutschland GmbH', 3],
['Karosseriewerke Dresden GmbH', 'Schnellecke Logistics Dingolfing GmbH', 1],
['Schnellecke Logistics Dingolfing GmbH', 'Karosseriewerke Dresden GmbH', 1],
['Schnellecke Logistics Dingolfing GmbH', 'KWD Automobiltechnik GmbH', 2],
['KWD Automobiltechnik GmbH', 'Schnellecke Logistics Dingolfing GmbH', 2],
['Karosseriewerke Dresden GmbH', 'MAN Truck & Bus AG', 1],
['MAN Truck & Bus AG', 'Karosseriewerke Dresden GmbH', 1],
['MAN Truck & Bus AG', 'NEOPLAN Bus GmbH', 3],
['NEOPLAN Bus GmbH', 'MAN Truck & Bus AG', 3],
['MAN Truck & Bus AG', 'MAN Finance International GmbH', 6],
['MAN Finance International GmbH', 'MAN Truck & Bus AG', 6],
['MAN Truck & Bus AG', 'AUDI AG', 2],
['AUDI AG', 'MAN Truck & Bus AG', 2],
['MAN Truck & Bus AG', 'MAN Diesel & Turbo SE', 16],
['MAN Diesel & Turbo SE', 'MAN Truck & Bus AG', 16],
['MAN Truck & Bus AG', 'MAN Versicherungsvermittlung GmbH', 3],
['MAN Versicherungsvermittlung GmbH', 'MAN Truck & Bus AG', 3],
['MAN Truck & Bus AG', 'MAN HR Services GmbH', 7],
['MAN HR Services GmbH', 'MAN Truck & Bus AG', 7],
['MAN Truck & Bus AG', 'MAN Service und Support GmbH', 6],
['MAN Service und Support GmbH', 'MAN Truck & Bus AG', 6],
['MAN Truck & Bus AG', 'MAN SE', 25],
['MAN SE', 'MAN Truck & Bus AG', 25],
['MAN Truck & Bus AG', 'MAN IT Services GmbH', 10],
['MAN IT Services GmbH', 'MAN Truck & Bus AG', 10],
['MAN Truck & Bus AG', 'KPMG AG Wirtschaftsprüfungsgesellschaft', 2],
['KPMG AG Wirtschaftsprüfungsgesellschaft', 'MAN Truck & Bus AG', 2],
['MAN Truck & Bus AG', 'Renk AG', 6],
['Renk AG', 'MAN Truck & Bus AG', 6],
['MAN Truck & Bus AG', 'MAN Financial Services GmbH', 4],
['MAN Financial Services GmbH', 'MAN Truck & Bus AG', 4],
['MAN Truck & Bus AG', 'MAN-Unterstützungskasse GmbH', 3],
['MAN-Unterstützungskasse GmbH', 'MAN Truck & Bus AG', 3],
['MAN Truck & Bus AG', 'Rheinmetall MAN Military Vehicles GmbH', 3],
['Rheinmetall MAN Military Vehicles GmbH', 'MAN Truck & Bus AG', 3],
['MAN Truck & Bus AG', 'MAN Truck & Bus Deutschland GmbH', 22],
['MAN Truck & Bus Deutschland GmbH', 'MAN Truck & Bus AG', 22],
['MAN Truck & Bus AG', 'MAN Verwaltungs-Gesellschaft mbH', 2],
['MAN Verwaltungs-Gesellschaft mbH', 'MAN Truck & Bus AG', 2],
['MAN Truck & Bus AG', 'MAN Grundstücksgesellschaft mbH', 3],
['MAN Grundstücksgesellschaft mbH', 'MAN Truck & Bus AG', 3],
['MAN Truck & Bus AG', 'MAN GHH Immobilien GmbH', 2],
['MAN GHH Immobilien GmbH', 'MAN Truck & Bus AG', 2],
['Karosseriewerke Dresden GmbH', 'Schnellecke Logistics AG & Co. KG', 1],
['Schnellecke Logistics AG & Co. KG', 'Karosseriewerke Dresden GmbH', 1],
['Schnellecke Logistics AG & Co. KG', 'Schnellecke Logistics Sachsen GmbH', 2],
['Schnellecke Logistics Sachsen GmbH', 'Schnellecke Logistics AG & Co. KG', 2],
['Schnellecke Logistics AG & Co. KG', 'Schnellecke Sachsen GmbH', 2],
['Schnellecke Sachsen GmbH', 'Schnellecke Logistics AG & Co. KG', 2],
['Schnellecke Logistics AG & Co. KG', 'Schnellecke Group AG & Co. KG', 9],
['Schnellecke Group AG & Co. KG', 'Schnellecke Logistics AG & Co. KG', 9],
];

var colors = {
"Karosseriewerke Dresden GmbH": "#da4480",
"AUDI AG": "#5ab449",
"Graf Treuhand GmbH Wirtschaftsprüfungsgesellschaft Steuerberatungsgesellschaft": "#7f5acd",
"KPMG AG Wirtschaftsprüfungsgesellschaft": "#aab740",
"KWD Automobiltechnik GmbH": "#ce58c0",
"KWD Automotive Verwaltungs GmbH": "#50a26e",
"MAN Diesel & Turbo SE": "#d1434b",
"MAN Finance International GmbH": "#45c0bc",
"MAN Financial Services GmbH": "#ce5929",
"MAN GHH Immobilien GmbH": "#4e7bda",
"MAN Grundstücksgesellschaft mbH": "#d49d3c",
"MAN HR Services GmbH": "#6660a3",
"MAN IT Services GmbH": "#7b853c",
"MAN SE": "#b58dde",
"MAN Service und Support GmbH": "#97622e",
"MAN Truck & Bus AG": "#609dd6",
"MAN Truck & Bus Deutschland GmbH": "#e29074",
"MAN Versicherungsvermittlung GmbH": "#9c4b88",
"MAN Verwaltungs-Gesellschaft mbH": "#ab505f",
"MAN-Unterstützungskasse GmbH": "#dc85b6",
"NEOPLAN Bus GmbH": "#5ab449",
"Renk AG": "#7f5acd",
"Rheinmetall MAN Military Vehicles GmbH": "#aab740",
"SCHNELLTRANS GmbH": "#ce58c0",
"ScanRo GmbH": "#50a26e",
"Scandlines Deutschland GmbH": "#d1434b",
"Scandlines Participation Verwaltungs GmbH": "#45c0bc",
"Schneider + Partner GmbH Wirtschaftsprüfungsgesellschaft Steuerberatungsgesellschaft": "#ce5929",
"Schnellecke Group AG & Co. KG": "#4e7bda",
"Schnellecke Logistics AG & Co. KG": "#d49d3c",
"Schnellecke Logistics Dingolfing GmbH": "#6660a3",
"Schnellecke Logistics Germany GmbH": "#7b853c",
"Schnellecke Logistics Sachsen GmbH": "#b58dde",
"Schnellecke Logistics Wolfsburg GmbH": "#97622e",
"Schnellecke Modul- und Lieferantenzentrum GmbH": "#609dd6",
"Schnellecke Sachsen GmbH": "#e29074",
};

var sortOrder = [
"Karosseriewerke Dresden GmbH",
"AUDI AG",
"Graf Treuhand GmbH Wirtschaftsprüfungsgesellschaft Steuerberatungsgesellschaft",
"KPMG AG Wirtschaftsprüfungsgesellschaft",
"KWD Automobiltechnik GmbH",
"KWD Automotive Verwaltungs GmbH",
"MAN Diesel & Turbo SE",
"MAN Finance International GmbH",
"MAN Financial Services GmbH",
"MAN GHH Immobilien GmbH",
"MAN Grundstücksgesellschaft mbH",
"MAN HR Services GmbH",
"MAN IT Services GmbH",
"MAN SE",
"MAN Service und Support GmbH",
"MAN Truck & Bus AG",
"MAN Truck & Bus Deutschland GmbH",
"MAN Versicherungsvermittlung GmbH",
"MAN Verwaltungs-Gesellschaft mbH",
"MAN-Unterstützungskasse GmbH",
"NEOPLAN Bus GmbH",
"Renk AG",
"Rheinmetall MAN Military Vehicles GmbH",
"SCHNELLTRANS GmbH",
"ScanRo GmbH",
"Scandlines Deutschland GmbH",
"Scandlines Participation Verwaltungs GmbH",
"Schneider + Partner GmbH Wirtschaftsprüfungsgesellschaft Steuerberatungsgesellschaft",
"Schnellecke Group AG & Co. KG",
"Schnellecke Logistics AG & Co. KG",
"Schnellecke Logistics Dingolfing GmbH",
"Schnellecke Logistics Germany GmbH",
"Schnellecke Logistics Sachsen GmbH",
"Schnellecke Logistics Wolfsburg GmbH",
"Schnellecke Modul- und Lieferantenzentrum GmbH",
"Schnellecke Sachsen GmbH",
];

function sort(a,b){ return d3.ascending(sortOrder.indexOf(a),sortOrder.indexOf(b)); }

var ch = viz.ch().data(data)
      .padding(.01)
      .sort(sort)
	  .innerRadius(330)
	  .outerRadius(350)
	  .duration(1000)
	  .chordOpacity(0.3)
	  .labelPadding(.03)
      .fill(function(d){ return colors[d];});

var width=1200, height=1100;

var svg = d3.select("body").append("svg").attr("height",height).attr("width",width);

svg.append("g").attr("transform", "translate(600,550)").call(ch);

// adjust height of frame in bl.ocks.org
d3.select(self.frameElement).style("height", height+"px").style("width", width+"px");  